# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-07-03 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrecioVenta', models.DecimalField(decimal_places=2, max_digits=6)),
                ('PrecioVentaCaja', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Detalle', models.CharField(blank=True, max_length=100, null=True)),
                ('Nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compra.Compra')),
            ],
        ),
    ]
