# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-07-03 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreProveedor', models.CharField(max_length=35)),
                ('Ruc', models.CharField(max_length=11)),
                ('Direccion', models.CharField(max_length=35)),
                ('Telefono', models.CharField(max_length=9)),
                ('DatosEncargado', models.CharField(max_length=35)),
                ('TelefonoEncargado', models.CharField(max_length=9)),
                ('FechaRegistro', models.DateField()),
            ],
        ),
    ]
