# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-07-03 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=25)),
                ('Apellidos', models.CharField(blank=True, max_length=25, null=True)),
                ('DNI', models.CharField(max_length=8, null=True)),
                ('Sexo', models.CharField(max_length=10)),
            ],
        ),
    ]
