# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-07-03 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreProducto', models.CharField(max_length=50)),
                ('PrecioCompra', models.PositiveSmallIntegerField()),
                ('Categoria', models.CharField(max_length=50)),
                ('Fecha', models.DateField()),
                ('CajaPaquete', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Detalle', models.CharField(blank=True, max_length=100, null=True)),
                ('Proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedor.Proveedor')),
            ],
        ),
    ]
