# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-07-03 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='PrecioCompra',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
