# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-07-03 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('producto', '0001_initial'),
        ('trabajador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaFactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Igv', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('FechaVenta', models.DateField()),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
                ('NombreTrabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajador.Trabajador')),
                ('Produc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Producto')),
            ],
        ),
    ]
